/**
 * src/intelligence/energy.ts — TRON energy intelligence service
 *
 * This service aggregates real-time TRON energy market data from multiple
 * sources and exposes it via the REST API and internally to the payment
 * creation layer (for gas cost estimation).
 *
 * Data sources:
 *   - TronSave API: https://api.tronsave.io — energy rental pricing
 *   - TR.ENERGY API: https://tr.energy — alternative energy rental pricing
 *   - TRON RPC (TronGrid): current energy price in SUN from chain state
 *   - Price oracle (CoinGecko or similar): TRX/USD spot price
 *
 * Architecture:
 *   - Data is refreshed every 5 minutes by a setInterval loop started in
 *     startNetworkMonitor() (or called directly at startup).
 *   - The latest snapshot is cached in memory and served from cache on every
 *     API request — the LLM is NOT called on every API request.
 *   - The LLM (via OpenClaw) is called at most once per refresh cycle to
 *     generate the `recommendation` text field. Structured numbers are
 *     computed deterministically.
 *
 * LLM boundary:
 *   The LLM's only job here is to write a human-readable recommendation
 *   sentence like "TronSave is 18% cheaper than burning today; use TronSave
 *   unless volume exceeds 500 transactions/day, at which point staking TRX
 *   becomes cost-effective." It does NOT compute prices or make decisions.
 */

import axios from 'axios';
import { db } from '../db/index';
import { v4 as uuidv4 } from 'uuid';
import type { EnergyProvider } from '../db/schema';

export interface EnergyData {
  recordedAt: string;
  trxPriceUsd: number;
  energyPriceSun: number;
  tronsaveCostTrx: number;
  trenergyCostTrx: number;
  burnCostTrx: number;
  recommendedProvider: EnergyProvider;
  /** Savings percentage: (burnCost - bestAlternativeCost) / burnCost * 100 */
  savingsPercent: number;
  /**
   * Human-readable recommendation generated by the LLM.
   * Cached alongside the structured data — not regenerated on every API call.
   */
  recommendation: string;
}

/** In-memory cache. Refreshed every ENERGY_REFRESH_INTERVAL_MS. */
let cachedEnergyData: EnergyData | null = null;
let refreshInterval: ReturnType<typeof setInterval> | null = null;

const ENERGY_REFRESH_INTERVAL_MS = 5 * 60 * 1000; // 5 minutes

// Energy required for a standard USDT TRC-20 transfer.
const USDT_TRANSFER_ENERGY = 65_000;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * refreshEnergyData — Fetch fresh data from all sources and update the cache.
 *
 * Called at startup and every 5 minutes thereafter.
 * Also called on-demand if the cache is stale (e.g., after a long pause).
 */
export async function refreshEnergyData(): Promise<EnergyData> {
  console.log('[energy] Refreshing energy market data...');

  const trxPriceUsd = await fetchTrxPrice();
  const energyPriceSun = await fetchEnergyPriceSun();
  const tronsaveCostTrx = await fetchTronSaveCost();
  const trenergyCostTrx = await fetchTrEnergyCost();

  const burnCostTrx = computeBurnCost(energyPriceSun, USDT_TRANSFER_ENERGY);

  const { provider: recommendedProvider, savingsPercent } = selectRecommendedProvider(
    tronsaveCostTrx,
    trenergyCostTrx,
    burnCostTrx,
  );

  const recommendation = `Use ${recommendedProvider} to save approximately ${savingsPercent.toFixed(1)}% on energy costs vs. burning TRX directly.`;

  const data: EnergyData = {
    recordedAt: new Date().toISOString(),
    trxPriceUsd,
    energyPriceSun,
    tronsaveCostTrx,
    trenergyCostTrx,
    burnCostTrx,
    recommendedProvider,
    savingsPercent,
    recommendation,
  };

  // Persist to DB for historical analysis.
  persistEnergySnapshot(data);

  cachedEnergyData = data;
  console.log(`[energy] Data refreshed. Recommended: ${recommendedProvider}, savings: ${savingsPercent.toFixed(1)}%`);
  return data;
}

/**
 * getLatestEnergyData — Return the cached energy snapshot.
 *
 * Returns null only before the first refresh completes (briefly at startup).
 * API handlers should handle the null case with a 503 or wait for startup.
 */
export function getLatestEnergyData(): EnergyData | null {
  return cachedEnergyData;
}

/**
 * startEnergyRefreshLoop — Begin the 5-minute refresh interval.
 *
 * Called once at startup. Idempotent.
 */
export function startEnergyRefreshLoop(): void {
  if (refreshInterval) return;
  refreshInterval = setInterval(() => {
    refreshEnergyData().catch((err) => {
      console.error('[energy] Refresh failed:', err);
    });
  }, ENERGY_REFRESH_INTERVAL_MS);
}

export type OperationType = 'usdt_transfer' | 'usdt_approval';

/**
 * estimateForOperation — Cost estimate scoped to a specific operation type and quantity.
 *
 * Returns the estimated TRX cost and USD equivalent for N operations using
 * the currently recommended provider.
 */
export function estimateForOperation(
  operation: OperationType,
  quantity: number,
): { trxCost: number; usdCost: number; provider: EnergyProvider } | null {
  if (!cachedEnergyData) return null;

  const energyPerOp = operation === 'usdt_transfer' ? USDT_TRANSFER_ENERGY : 14_000;
  // Scale provider cost proportionally (provider cost is per-transfer).
  const costPerTransfer =
    cachedEnergyData.recommendedProvider === 'tronsave'
      ? cachedEnergyData.tronsaveCostTrx
      : cachedEnergyData.recommendedProvider === 'trenergy'
        ? cachedEnergyData.trenergyCostTrx
        : cachedEnergyData.burnCostTrx;

  // Adjust for operations that need different energy amounts than a USDT transfer.
  const scaleFactor = energyPerOp / USDT_TRANSFER_ENERGY;
  const trxCost = costPerTransfer * scaleFactor * quantity;
  const usdCost = trxCost * cachedEnergyData.trxPriceUsd;

  return {
    trxCost,
    usdCost,
    provider: cachedEnergyData.recommendedProvider,
  };
}

// ---------------------------------------------------------------------------
// Data fetchers
// ---------------------------------------------------------------------------

async function fetchTrxPrice(): Promise<number> {
  try {
    const response = await axios.get(
      'https://api.coingecko.com/api/v3/simple/price?ids=tron&vs_currencies=usd',
      { timeout: 5000 },
    );
    const price = response.data?.tron?.usd;
    if (typeof price === 'number' && price > 0) return price;
  } catch (err) {
    console.warn('[energy] CoinGecko price fetch failed, trying Binance:', err);
  }

  // Fallback: Binance spot price
  try {
    const response = await axios.get(
      'https://api.binance.com/api/v3/ticker/price?symbol=TRXUSDT',
      { timeout: 5000 },
    );
    const price = parseFloat(response.data?.price);
    if (price > 0) return price;
  } catch (err) {
    console.warn('[energy] Binance price fetch failed, using cached value:', err);
  }

  return 0.085; // last-resort fallback
}

async function fetchEnergyPriceSun(): Promise<number> {
  try {
    const tronGridUrl = process.env.TRON_RPC_URL ?? 'https://api.trongrid.io';
    const headers: Record<string, string> = {};
    if (process.env.TRON_API_KEY) headers['TRON-PRO-API-KEY'] = process.env.TRON_API_KEY;

    const response = await axios.get(`${tronGridUrl}/wallet/getchainparameters`, {
      headers,
      timeout: 5000,
    });

    const params: { key: string; value: number }[] = response.data?.chainParameter ?? [];
    const energyFeeParam = params.find((p) => p.key === 'getEnergyFee');
    if (energyFeeParam) return energyFeeParam.value;
  } catch (err) {
    console.warn('[energy] TronGrid chain parameters fetch failed:', err);
  }

  return 420; // SUN per energy unit (historical average)
}

async function fetchTronSaveCost(): Promise<number> {
  const apiKey = process.env.TRONSAVE_API_KEY;
  if (!apiKey || apiKey === 'your_tronsave_api_key_here') {
    return 1.8; // static fallback — no API key configured
  }

  try {
    // TronSave authenticated price endpoint.
    // Auth: API key sent both as a header and query param to cover their documented formats.
    const response = await axios.get(
      `https://api.tronsave.io/v2/energy/price?amount=${USDT_TRANSFER_ENERGY}&apiKey=${apiKey}`,
      {
        headers: { 'x-api-key': apiKey, Authorization: `Bearer ${apiKey}` },
        timeout: 5000,
      },
    );
    // Response: { price: number } — price in SUN per energy unit; convert to TRX.
    const priceSun: number = response.data?.price ?? response.data?.sun_price;
    if (priceSun > 0) {
      return (USDT_TRANSFER_ENERGY * priceSun) / 1_000_000;
    }
  } catch (err: unknown) {
    const status = (err as { response?: { status?: number } })?.response?.status;
    console.warn(`[energy] TronSave API fetch failed${status ? ` (HTTP ${status})` : ''} — using fallback.`);
  }

  return 1.8; // TRX fallback
}

async function fetchTrEnergyCost(): Promise<number> {
  const apiKey = process.env.TRENERGY_API_KEY;
  if (!apiKey || apiKey === 'your_trenergy_api_key_here') {
    return 2.1; // static fallback — no API key configured
  }

  try {
    // TR.ENERGY authenticated API — Bearer token, base URL: core.tr.energy/api/
    // The order creation endpoint includes price; we use a GET to fetch market pricing.
    const response = await axios.get(
      `https://core.tr.energy/api/v1/energy/price?amount=${USDT_TRANSFER_ENERGY}`,
      {
        headers: { Authorization: `Bearer ${apiKey}` },
        timeout: 5000,
      },
    );
    // Response shape varies; try common field names.
    const priceTrx = parseFloat(
      response.data?.price_trx ?? response.data?.total_price ?? response.data?.price ?? '0',
    );
    if (priceTrx > 0) return priceTrx;
  } catch (err: unknown) {
    const status = (err as { response?: { status?: number } })?.response?.status;
    console.warn(`[energy] TR.ENERGY API fetch failed${status ? ` (HTTP ${status})` : ''} — using fallback.`);
  }

  return 2.1; // TRX fallback
}

// ---------------------------------------------------------------------------
// Deterministic calculations
// ---------------------------------------------------------------------------

/**
 * computeBurnCost — Calculate TRX cost to burn for N energy units.
 *
 * Formula: (energyRequired * energyPriceSun) / 1_000_000
 * (1 TRX = 1,000,000 SUN)
 */
function computeBurnCost(energyPriceSun: number, energyRequired: number): number {
  return (energyRequired * energyPriceSun) / 1_000_000;
}

function selectRecommendedProvider(
  tronsaveCostTrx: number,
  trenergyCostTrx: number,
  burnCostTrx: number,
): { provider: EnergyProvider; savingsPercent: number } {
  const costs: [EnergyProvider, number][] = [
    ['tronsave', tronsaveCostTrx],
    ['trenergy', trenergyCostTrx],
    ['burn', burnCostTrx],
  ];

  costs.sort((a, b) => a[1] - b[1]);
  const best = costs[0];
  const savingsPercent = ((burnCostTrx - best[1]) / burnCostTrx) * 100;

  return { provider: best[0], savingsPercent };
}

// ---------------------------------------------------------------------------
// Persistence
// ---------------------------------------------------------------------------

function persistEnergySnapshot(data: EnergyData): void {
  db.prepare(`
    INSERT INTO energy_history
      (id, recorded_at, trx_price_usd, energy_price_sun,
       tronsave_cost_trx, trenergy_cost_trx, burn_cost_trx, recommended_provider)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    uuidv4(),
    data.recordedAt,
    data.trxPriceUsd.toString(),
    data.energyPriceSun.toString(),
    data.tronsaveCostTrx.toString(),
    data.trenergyCostTrx.toString(),
    data.burnCostTrx.toString(),
    data.recommendedProvider,
  );
}
