/**
 * src/db/schema.ts — Database schema definitions
 *
 * Two things live here:
 *   1. SQL strings used to CREATE tables on first run (idempotent).
 *   2. TypeScript interfaces that mirror every table row — used throughout
 *      the codebase for type-safe DB access.
 *
 * Design notes:
 *   - All timestamps are stored as ISO-8601 strings (TEXT) for SQLite
 *     compatibility. Use new Date().toISOString() when writing, and
 *     new Date(row.created_at) when reading.
 *   - Monetary amounts are stored as TEXT (decimal strings) to avoid
 *     IEEE-754 floating-point precision loss. Use a decimal library when
 *     performing arithmetic; never use JS Number for money.
 *   - All primary keys are UUIDs (TEXT) generated by the application layer
 *     except address_pool which uses the HD derivation index as its PK.
 */

// ---------------------------------------------------------------------------
// TypeScript row interfaces
// ---------------------------------------------------------------------------

/** A developer who has registered to use the relay API. */
export interface Developer {
  id: string;
  /** 32-byte hex string, generated at registration, passed as X-Api-Key. */
  api_key: string;
  /** The TRON address where the developer wants to receive net payments. */
  receiving_address: string;
  /**
   * Which chain the developer receives payouts on.
   * 'tron'  — receive USDT directly on Tron (default, no bridging).
   * 'base'  — receive USDC on Base via deBridge DLN (extra bridge fee applies).
   */
  payout_chain: 'tron' | 'base';
  /**
   * Developer's Base address for USDC payout. Required when payout_chain = 'base'.
   * Null when payout_chain = 'tron'.
   */
  base_receiving_address: string | null;
  /** URL the relay POSTs payment events to. */
  webhook_url: string;
  /** Secret used to sign webhook payloads (HMAC-SHA256). */
  webhook_secret: string;
  created_at: string;
  /** Soft-delete flag. Inactive developers' new payment requests are rejected. */
  is_active: number; // 1 = true, 0 = false (SQLite has no BOOLEAN type)
}

export type PaymentStatus =
  | 'pending'    // address assigned, waiting for user to send
  | 'detected'   // USDT arrived on-chain, awaiting confirmations
  | 'confirmed'  // 3 confirmations reached, forwarding triggered
  | 'bridging'   // funds swept to relay hot wallet; cross-chain bridge initiated (Base payout)
  | 'forwarded'  // funds delivered to developer (Tron tx or bridge fulfillment confirmed)
  | 'expired'    // expiresAt passed without payment arriving
  | 'failed';    // forwarding or webhook delivery permanently failed

/** An individual payment request created by a developer. */
export interface Payment {
  id: string;
  developer_id: string;
  /** Developer's own reference ID for their order; returned in webhooks. */
  order_id: string;
  /** The TRON address the user should send USDT to. */
  address: string;
  /** HD derivation index that produced `address`. Used to sign the sweep tx. */
  address_index: number;
  /**
   * Amount the user must send (decimal string, e.g. "10.30").
   * Includes the relay fee and gasless sponsorship cost if applicable.
   */
  amount_due: string;
  /**
   * Amount the developer receives after fees (decimal string).
   * = amount_due - relay_fee - sponsorship_cost
   */
  amount_net: string;
  currency: 'USDT';
  status: PaymentStatus;
  /** Set once the transaction is detected on-chain. */
  tx_hash: string | null;
  /** Current confirmation count. Updated by the monitor loop. */
  confirmations: number;
  created_at: string;
  /** Set when the monitor first sees the inbound transfer on-chain. Used for confirmation timing measurements. */
  detected_at: string | null;
  /** Set when status transitions to 'confirmed'. */
  confirmed_at: string | null;
  /** Payments not detected before this time are expired by the cleanup job. */
  expires_at: string;
}

export type AddressStatus = 'available' | 'in_use' | 'recycling';

/** Tracks which HD-derived addresses are available or in use. */
export interface AddressPoolEntry {
  /**
   * The BIP-44 derivation index. Also the primary key.
   * Named `idx` to match the SQL column (avoids collision with the JS reserved
   * property `index` on array-like objects, and `INDEX` is a reserved SQL keyword).
   */
  idx: number;
  address: string;
  status: AddressStatus;
  /** Foreign key to payments.id when status = 'in_use'. */
  payment_id: string | null;
  last_used_at: string | null;
}

/** One observed confirmation-time measurement from a completed relay. */
export interface ConfirmationTime {
  id: string;
  payment_id: string;
  /** When the forwarding transaction was broadcast to the TRON network. */
  broadcast_at: string;
  /** When the monitor first detected the inbound transfer on-chain. */
  detected_at: string;
  /** When 3 confirmations were reached. */
  confirmed_at: string;
  /** Derived: (confirmed_at - detected_at) in seconds. Stored for fast percentile queries. */
  confirmation_seconds: number;
  block_height: number;
}

export type EnergyProvider = 'tronsave' | 'trenergy' | 'burn';

/** One snapshot of TRON energy market prices. Collected every 5 minutes. */
export interface EnergyHistory {
  id: string;
  recorded_at: string;
  /** USD price of 1 TRX at time of snapshot. */
  trx_price_usd: string;
  /** Current energy price in SUN (from TRON RPC). */
  energy_price_sun: string;
  /** Cost of 65,000 energy (one USDT transfer) from TronSave, in TRX. */
  tronsave_cost_trx: string;
  /** Same from TR.ENERGY. */
  trenergy_cost_trx: string;
  /** Burn cost: energy_price_sun * 65000 / 1e6, in TRX. */
  burn_cost_trx: string;
  /** Which provider was cheapest at this snapshot. */
  recommended_provider: EnergyProvider;
}

export type ExperimentStatus = 'pending' | 'evaluated';

/**
 * An experiment the agent created to test a hypothesis.
 * Follows the scientific method: hypothesis → decision → metric → outcome.
 */
export interface Experiment {
  id: string;
  created_at: string;
  /** Free-text description of the situation that prompted the experiment. */
  context: string;
  /** Testable prediction: "if I do X, metric Y will change by Z". */
  hypothesis: string;
  /** What action was taken as a result of this experiment. */
  decision: string;
  /** The metric name to evaluate the outcome against. */
  metric: string;
  /** ISO date string — when the agent should evaluate the outcome. */
  check_date: string;
  /** What actually happened. Filled in by the agent at evaluation. */
  outcome: string | null;
  /** What the agent learned from the experiment. */
  learning: string | null;
  status: ExperimentStatus;
}

/**
 * A persisted key-value setting. Used for runtime configuration that must
 * survive process restarts (e.g., the agent-adjusted relay fee).
 *
 * Design: intentionally simple. If the number of settings grows significantly,
 * consider a typed config table instead. For now, all values are stored as TEXT
 * and parsed by the caller.
 */
export interface Setting {
  key: string;
  value: string;
  updated_at: string;
}

/** Known setting keys — kept here so callers have autocomplete. */
export const SETTING_KEYS = {
  RELAY_FEE_PERCENT: 'relay_fee_percent',
  /** Aave aToken balance at start of day. Written at each 23:55 rollup for next-day yield calc. */
  AAVE_SOD_BALANCE_USDT: 'aave_sod_balance_usdt',
} as const;

/** Daily rolled-up financial and operational metrics. */
export interface MetricsDaily {
  /** ISO date string (YYYY-MM-DD). Primary key. */
  date: string;
  /** Total x402 USDC fees collected that day (decimal string). */
  revenue_usdc: string;
  /** Total relay fees collected in USDT that day (decimal string). */
  revenue_usdt: string;
  transaction_count: number;
  avg_confirmation_seconds: number;
  /** Number of OpenClaw/LLM sessions invoked. */
  llm_calls: number;
  /** Estimated USD cost of all LLM inference that day (decimal string). */
  llm_cost_usd: string;
  /** Aave yield earned that day (decimal string). */
  aave_yield_usdt: string;
  /** Liquid USDT balance at end-of-day snapshot. */
  wallet_balance_usdt: string;
  /** USDC balance on Base at end-of-day snapshot. */
  wallet_balance_usdc: string;
}

// ---------------------------------------------------------------------------
// SQL CREATE statements (all idempotent via IF NOT EXISTS)
// ---------------------------------------------------------------------------

export const CREATE_DEVELOPERS = `
  CREATE TABLE IF NOT EXISTS developers (
    id                     TEXT PRIMARY KEY,
    api_key                TEXT NOT NULL UNIQUE,
    receiving_address      TEXT NOT NULL,
    payout_chain           TEXT NOT NULL DEFAULT 'tron',
    base_receiving_address TEXT,
    webhook_url            TEXT NOT NULL,
    webhook_secret         TEXT NOT NULL,
    created_at             TEXT NOT NULL,
    is_active              INTEGER NOT NULL DEFAULT 1
  )
`;

export const CREATE_PAYMENTS = `
  CREATE TABLE IF NOT EXISTS payments (
    id               TEXT PRIMARY KEY,
    developer_id     TEXT NOT NULL REFERENCES developers(id),
    order_id         TEXT NOT NULL,
    address          TEXT NOT NULL,
    address_index    INTEGER NOT NULL,
    amount_due       TEXT NOT NULL,
    amount_net       TEXT NOT NULL,
    currency         TEXT NOT NULL DEFAULT 'USDT',
    status           TEXT NOT NULL DEFAULT 'pending',
    tx_hash          TEXT,
    confirmations    INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT NOT NULL,
    detected_at      TEXT,
    confirmed_at     TEXT,
    expires_at       TEXT NOT NULL
  )
`;

export const CREATE_ADDRESS_POOL = `
  CREATE TABLE IF NOT EXISTS address_pool (
    idx              INTEGER PRIMARY KEY,
    address          TEXT NOT NULL UNIQUE,
    status           TEXT NOT NULL DEFAULT 'available',
    payment_id       TEXT REFERENCES payments(id),
    last_used_at     TEXT
  )
`;

export const CREATE_CONFIRMATION_TIMES = `
  CREATE TABLE IF NOT EXISTS confirmation_times (
    id                   TEXT PRIMARY KEY,
    payment_id           TEXT NOT NULL REFERENCES payments(id),
    broadcast_at         TEXT NOT NULL,
    detected_at          TEXT NOT NULL,
    confirmed_at         TEXT NOT NULL,
    confirmation_seconds INTEGER NOT NULL,
    block_height         INTEGER NOT NULL
  )
`;

export const CREATE_ENERGY_HISTORY = `
  CREATE TABLE IF NOT EXISTS energy_history (
    id                    TEXT PRIMARY KEY,
    recorded_at           TEXT NOT NULL,
    trx_price_usd         TEXT NOT NULL,
    energy_price_sun      TEXT NOT NULL,
    tronsave_cost_trx     TEXT NOT NULL,
    trenergy_cost_trx     TEXT NOT NULL,
    burn_cost_trx         TEXT NOT NULL,
    recommended_provider  TEXT NOT NULL
  )
`;

export const CREATE_EXPERIMENTS = `
  CREATE TABLE IF NOT EXISTS experiments (
    id          TEXT PRIMARY KEY,
    created_at  TEXT NOT NULL,
    context     TEXT NOT NULL,
    hypothesis  TEXT NOT NULL,
    decision    TEXT NOT NULL,
    metric      TEXT NOT NULL,
    check_date  TEXT NOT NULL,
    outcome     TEXT,
    learning    TEXT,
    status      TEXT NOT NULL DEFAULT 'pending'
  )
`;

export const CREATE_METRICS_DAILY = `
  CREATE TABLE IF NOT EXISTS metrics_daily (
    date                    TEXT PRIMARY KEY,
    revenue_usdc            TEXT NOT NULL DEFAULT '0',
    revenue_usdt            TEXT NOT NULL DEFAULT '0',
    transaction_count       INTEGER NOT NULL DEFAULT 0,
    avg_confirmation_seconds REAL NOT NULL DEFAULT 0,
    llm_calls               INTEGER NOT NULL DEFAULT 0,
    llm_cost_usd            TEXT NOT NULL DEFAULT '0',
    aave_yield_usdt         TEXT NOT NULL DEFAULT '0',
    wallet_balance_usdt     TEXT NOT NULL DEFAULT '0',
    wallet_balance_usdc     TEXT NOT NULL DEFAULT '0'
  )
`;

export const CREATE_SETTINGS = `
  CREATE TABLE IF NOT EXISTS settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )
`;

export const CREATE_AGENT_LOGS = `
  CREATE TABLE IF NOT EXISTS agent_logs (
    id         TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    level      TEXT NOT NULL,
    category   TEXT NOT NULL,
    message    TEXT NOT NULL,
    data       TEXT
  )
`;

/** All CREATE statements in dependency order (referenced tables first). */
export const ALL_SCHEMA_STATEMENTS = [
  CREATE_DEVELOPERS,
  CREATE_PAYMENTS,
  CREATE_ADDRESS_POOL,
  CREATE_CONFIRMATION_TIMES,
  CREATE_ENERGY_HISTORY,
  CREATE_EXPERIMENTS,
  CREATE_METRICS_DAILY,
  CREATE_SETTINGS,
  CREATE_AGENT_LOGS,
] as const;
